name: entao_config
description: dart config file with struct formats.
version: 1.1.0
repository: https://github.com/yangentao/entao_config
homepage: https://github.com/yangentao/entao_config

environment:
  sdk: ^3.6.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  entao_lint: ^1.0.1
  entao_dutil: ^2.3.4
  println: ^1.0.4
dev_dependencies:
  #  println: ^1.0.4
  lints: ^6.0.0
  test: ^1.25.6
